### PR TITLE
Add OAuth support for Google

### PR DESCRIPTION
**Pull request by viktorsat**
This PR will provide an OAuth support by utilizing the allauth django library. At the moment only google is added as a provider but in the future this can be configured to utilize other providers like facebook etc...

### CODE REVIEW

**Comment by horilla-opensource** [comment]
Hi @viktorsat,  

Thank you for your valuable contribution! We truly appreciate the time and effort you’ve put into it.  

Our team is currently reviewing the commits, and we will provide you with an update once the review is complete.  

Best regards,  
**Team Horilla**

**Comment by viktorsat** [comment]
Any updates here? @horilla-opensource

**Comment by horilla-opensource** [comment]
Hi @viktorsat,  

Thank you so much for your valuable contribution! We truly appreciate the time and effort you’ve dedicated to improving Horilla. Your work is a great addition, and the team has reviewed the code thoroughly. Overall, it looks great.  

That said, we do have some concerns regarding the compatibility of this feature with Horilla’s core HR system. Since Horilla is a self-hosted solution designed for firms managing their internal employee data, enabling login via Google accounts might pose challenges. Specifically, if the system is publicly accessible, it could allow external individuals to log in, which might compromise the intended privacy of the deployment.  

To address this, we are exploring ways to include this feature while maintaining flexibility and security. One option we are considering is allowing admins to enable or disable Google authentication based on their preferences. Additionally, we’re looking into restricting Google authentication to specific email domains to safeguard internal data.  

Once we finalize the implementation strategy, we’ll keep you updated. Thank you again for your contribution, and we look forward to more collaborations in the future!  

With Regards,  
**Team Horilla**

**Comment by viktorsat** [comment]
Thanks for the feedback, really appreciate it!

**Pull request closed without merging**
