### PR TITLE
Added production settings and support for secret values from env variables

### PR DESCRIPTION
**Pull request by ashwanthbalakrishnan5**
- Added production settings 
- Support for Environment variables using django-environ
- Option to set Database settings from db url 

i.e. DATABASE_URL=postgresql://user:password@localhost:5432/dbname

### CODE REVIEW

**Comment by ashwanthbalakrishnan5** [comment]
Need to update Readme file accordingly.

.env.dist is just a sample file, the main file should ".env".

**Comment by ashwanthbalakrishnan5** [comment]
Updated with minor bug fix

**Comment by ashwanthbalakrishnan5** [comment]
Hi @horilla-opensource,
Any updates on this ?

**Comment by horilla-opensource** [comment]
Hi @ashwanthbalakrishnan5 ,
Our team is verifying this PR.
Will give an update soon.

With Regards,
**Team Horilla**

**Pull request merged**
